# Shell variables
# Generated by 'wal'
wallpaper='/home/frederick/.config/sunpaper/images/fakuria-design/5.jpg'

# Special
background='#faf0ee'
foreground='#0C0A2D'
cursor='#0C0A2D'

# Colors
color0='#faf0ee'
color1='#9F422A'
color2='#AF4D2A'
color3='#CD6926'
color4='#D16D24'
color5='#9B5272'
color6='#E58425'
color7='#0C0A2D'
color8='#886056'
color9='#9F422A'
color10='#AF4D2A'
color11='#CD6926'
color12='#D16D24'
color13='#9B5272'
color14='#E58425'
color15='#0C0A2D'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
